/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewer;

/**
 *
 * @author Vinip
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastro = new javax.swing.JPanel();
        venhaParaAVaultBank = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelTelaCadastro = new javax.swing.JPanel();
        nomeCadastro = new javax.swing.JLabel();
        nomeTXT = new javax.swing.JTextField();
        labelCadstro = new javax.swing.JLabel();
        rGTXT = new javax.swing.JTextField();
        labelCpf = new javax.swing.JLabel();
        cpfText = new javax.swing.JTextField();
        labelCpf1 = new javax.swing.JLabel();
        labelCpf2 = new javax.swing.JLabel();
        cpfText1 = new javax.swing.JTextField();
        labelCpf3 = new javax.swing.JLabel();
        cpfText2 = new javax.swing.JTextField();
        labelCpf4 = new javax.swing.JLabel();
        nomeCadastro1 = new javax.swing.JLabel();
        nomeCadastro2 = new javax.swing.JLabel();
        cpfText3 = new javax.swing.JTextField();
        labelCpf5 = new javax.swing.JLabel();
        cpfText4 = new javax.swing.JTextField();
        labelCpf6 = new javax.swing.JLabel();
        telefoneText = new javax.swing.JTextField();
        cepLabel = new javax.swing.JLabel();
        cepText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCadastro.setBackground(new java.awt.Color(242, 218, 172));

        venhaParaAVaultBank.setBackground(new java.awt.Color(217, 165, 11));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENHA PARA A VAULTBANK");

        javax.swing.GroupLayout venhaParaAVaultBankLayout = new javax.swing.GroupLayout(venhaParaAVaultBank);
        venhaParaAVaultBank.setLayout(venhaParaAVaultBankLayout);
        venhaParaAVaultBankLayout.setHorizontalGroup(
            venhaParaAVaultBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(venhaParaAVaultBankLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        venhaParaAVaultBankLayout.setVerticalGroup(
            venhaParaAVaultBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(venhaParaAVaultBankLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        painelTelaCadastro.setBackground(new java.awt.Color(242, 206, 22));
        painelTelaCadastro.setForeground(new java.awt.Color(242, 206, 22));

        nomeCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomeCadastro.setForeground(new java.awt.Color(0, 0, 0));
        nomeCadastro.setText("Dados Pessoais");

        nomeTXT.setBackground(new java.awt.Color(115, 185, 221));
        nomeTXT.setForeground(new java.awt.Color(255, 255, 255));
        nomeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTXTActionPerformed(evt);
            }
        });

        labelCadstro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCadstro.setForeground(new java.awt.Color(255, 255, 255));
        labelCadstro.setText("Cadastro");

        rGTXT.setBackground(new java.awt.Color(115, 185, 221));
        rGTXT.setForeground(new java.awt.Color(255, 255, 255));
        rGTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rGTXTActionPerformed(evt);
            }
        });

        labelCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCpf.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf.setText("CPF:");

        cpfText.setBackground(new java.awt.Color(115, 185, 221));
        cpfText.setForeground(new java.awt.Color(255, 255, 255));
        cpfText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextActionPerformed(evt);
            }
        });

        labelCpf1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCpf1.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf1.setText("RG:");

        labelCpf2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCpf2.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf2.setText("Nacionalidade:");

        cpfText1.setBackground(new java.awt.Color(115, 185, 221));
        cpfText1.setForeground(new java.awt.Color(255, 255, 255));
        cpfText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfText1ActionPerformed(evt);
            }
        });

        labelCpf3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCpf3.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf3.setText("Data de nascimento:");

        cpfText2.setBackground(new java.awt.Color(115, 185, 221));
        cpfText2.setForeground(new java.awt.Color(255, 255, 255));
        cpfText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfText2ActionPerformed(evt);
            }
        });

        labelCpf4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCpf4.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf4.setText("Email:");

        nomeCadastro1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeCadastro1.setForeground(new java.awt.Color(255, 255, 255));
        nomeCadastro1.setText("Nome:");

        nomeCadastro2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomeCadastro2.setForeground(new java.awt.Color(0, 0, 0));
        nomeCadastro2.setText("Contato");

        cpfText3.setBackground(new java.awt.Color(115, 185, 221));
        cpfText3.setForeground(new java.awt.Color(255, 255, 255));
        cpfText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfText3ActionPerformed(evt);
            }
        });

        labelCpf5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCpf5.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf5.setText("Estado:");

        cpfText4.setBackground(new java.awt.Color(115, 185, 221));
        cpfText4.setForeground(new java.awt.Color(255, 255, 255));
        cpfText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfText4ActionPerformed(evt);
            }
        });

        labelCpf6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCpf6.setForeground(new java.awt.Color(255, 255, 255));
        labelCpf6.setText("Telefone");

        telefoneText.setBackground(new java.awt.Color(115, 185, 221));
        telefoneText.setForeground(new java.awt.Color(255, 255, 255));
        telefoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneTextActionPerformed(evt);
            }
        });

        cepLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cepLabel.setForeground(new java.awt.Color(255, 255, 255));
        cepLabel.setText("CEP:");

        cepText.setBackground(new java.awt.Color(115, 185, 221));
        cepText.setForeground(new java.awt.Color(255, 255, 255));
        cepText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTelaCadastroLayout = new javax.swing.GroupLayout(painelTelaCadastro);
        painelTelaCadastro.setLayout(painelTelaCadastroLayout);
        painelTelaCadastroLayout.setHorizontalGroup(
            painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(labelCadstro))
                    .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                                .addComponent(labelCpf2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfText2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCpf3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfText1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                                    .addComponent(nomeCadastro1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                                    .addComponent(labelCpf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(labelCpf1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rGTXT))
                                .addComponent(nomeCadastro))
                            .addComponent(nomeCadastro2)
                            .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                                .addComponent(cepLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cepText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCpf5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfText4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                                .addComponent(labelCpf4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfText3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCpf6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        painelTelaCadastroLayout.setVerticalGroup(
            painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadstro)
                .addGap(13, 13, 13)
                .addComponent(nomeCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCadastro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rGTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf2)
                    .addComponent(cpfText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf3)
                    .addComponent(cpfText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(nomeCadastro2)
                .addGap(18, 18, 18)
                .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf4)
                    .addComponent(cpfText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf5)
                    .addComponent(cpfText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepLabel)
                    .addComponent(cepText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(venhaParaAVaultBank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(painelTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addComponent(venhaParaAVaultBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(painelTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTXTActionPerformed

    private void rGTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rGTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rGTXTActionPerformed

    private void cpfTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextActionPerformed

    private void cpfText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfText1ActionPerformed

    private void cpfText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfText2ActionPerformed

    private void cpfText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfText3ActionPerformed

    private void cpfText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfText4ActionPerformed

    private void telefoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneTextActionPerformed

    private void cepTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField cepText;
    private javax.swing.JTextField cpfText;
    private javax.swing.JTextField cpfText1;
    private javax.swing.JTextField cpfText2;
    private javax.swing.JTextField cpfText3;
    private javax.swing.JTextField cpfText4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCadstro;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelCpf1;
    private javax.swing.JLabel labelCpf2;
    private javax.swing.JLabel labelCpf3;
    private javax.swing.JLabel labelCpf4;
    private javax.swing.JLabel labelCpf5;
    private javax.swing.JLabel labelCpf6;
    private javax.swing.JLabel nomeCadastro;
    private javax.swing.JLabel nomeCadastro1;
    private javax.swing.JLabel nomeCadastro2;
    private javax.swing.JTextField nomeTXT;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel painelTelaCadastro;
    private javax.swing.JTextField rGTXT;
    private javax.swing.JTextField telefoneText;
    private javax.swing.JPanel venhaParaAVaultBank;
    // End of variables declaration//GEN-END:variables
}
